server:
  port: 18892

spring:
  datasource:
    url: jdbc:mysql://47.98.202.59:3306/electric_monitor?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: root
    password: 1012xiao
  data:
    mongodb:
      host: 47.98.202.59
      database: electric_monitor
      username: admin
      password: electricMonitor
  redis:
    host: 47.98.202.59
    database: 4
    password: 1012xiao
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
